"""api pilot schema

Revision ID: 0001
Revises: 
Create Date: 2026-06-13 12:55:38.692469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('headers_json', sa.JSON(), nullable=False),
    sa.Column('variables_json', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('api_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('headers_json', sa.JSON(), nullable=False),
    sa.Column('query_json', sa.JSON(), nullable=False),
    sa.Column('body_json', sa.JSON(), nullable=True),
    sa.Column('assertions_json', sa.JSON(), nullable=False),
    sa.Column('extractors_json', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_cases_project_id'), ['project_id'], unique=False)

    op.create_table('test_suites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('draft_revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_suites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_suites_project_id'), ['project_id'], unique=False)

    op.create_table('suite_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['api_cases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suite_id', 'position', name='uq_suite_step_position')
    )
    with op.batch_alter_table('suite_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suite_steps_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suite_steps_suite_id'), ['suite_id'], unique=False)

    op.create_table('suite_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('source_revision', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suite_id', 'version_number', name='uq_suite_version_number')
    )
    with op.batch_alter_table('suite_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suite_versions_suite_id'), ['suite_id'], unique=False)

    op.create_table('test_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('suite_id', sa.Integer(), nullable=True),
    sa.Column('suite_version_id', sa.Integer(), nullable=True),
    sa.Column('draft_revision', sa.Integer(), nullable=True),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.Enum('FORM_SUITE', 'PYTHON_TESTS', name='runsourcetype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'PASSED', 'FAILED', 'CANCELLED', 'ERROR', 'INTERRUPTED', name='runstatus', native_enum=False), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suite_version_id'], ['suite_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_runs_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_runs_suite_id'), ['suite_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_runs_suite_version_id'), ['suite_version_id'], unique=False)

    op.create_table('case_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('case_key', sa.String(length=512), nullable=False),
    sa.Column('case_name', sa.String(length=255), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'FAILED', 'SKIPPED', 'ERROR', name='caseresultstatus', native_enum=False), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('request_json', sa.JSON(), nullable=True),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('assertions_json', sa.JSON(), nullable=False),
    sa.Column('extracted_variables_json', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'case_key', name='uq_run_case_key')
    )
    with op.batch_alter_table('case_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_results_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_results_run_id'))

    op.drop_table('case_results')
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_runs_suite_version_id'))
        batch_op.drop_index(batch_op.f('ix_test_runs_suite_id'))
        batch_op.drop_index(batch_op.f('ix_test_runs_status'))
        batch_op.drop_index(batch_op.f('ix_test_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_test_runs_environment_id'))

    op.drop_table('test_runs')
    with op.batch_alter_table('suite_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suite_versions_suite_id'))

    op.drop_table('suite_versions')
    with op.batch_alter_table('suite_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suite_steps_suite_id'))
        batch_op.drop_index(batch_op.f('ix_suite_steps_case_id'))

    op.drop_table('suite_steps')
    with op.batch_alter_table('test_suites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_suites_project_id'))

    op.drop_table('test_suites')
    with op.batch_alter_table('api_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_cases_project_id'))

    op.drop_table('api_cases')
    op.drop_table('projects')
    op.drop_table('environments')
    # ### end Alembic commands ###
